---
title: "ADAfaEPoVAK"
author: "Robert A. Stevens"
date: "November 9, 2016"
output: html_document
---

*Advanced Data Analysis from an Elementary Point of View*

by Cosma Rohilla Shalizi

# Appendix K: Rudimentary Graph Theory

A graph G is built out of a set of nodes or vertices, and edges or links connecting them. The edges can either be directed or undirected. A graph with undirected edges, or an undirected graph, represents a symmetric binary relation among the nodes. For instance, in a social network, the nodes might be people, and the relationship might be “spends time with”. A graph with directed edges, or arrows, is called a directed graph or digraph [1], and represents an asymmetric relation among the nodes. To continue the social example, the arrows might mean “admires”, pointing from the admirer to the object of admiration. If the relationship is reciprocal, that is indicated by drawing a pair of arrows between the nodes, one in each direction (as between A and B in Figure K.1).

FIGURE K.1: Example for illustrating the concepts of graph theory.

A directed path from node V1 to node V2 is a sequence of edges, beginning at V1 and ending at V2, which is connected and which follows the orientation of the edges at each step. An undirected path is a sequence of connected edges ignoring orientation. (Every path in an undirected graph is undirected.) If there is a directed path from V1 to V2 and from V2 to V1, then those two nodes are strongly connected. (In Figure K.1, A and C are strongly connected, but A and D are not.) If there are undirected paths in both directions, they are weakly connected. (A and D are weakly connected.) Strong connection implies weak connection. (EXERCISE: Prove this.) We also stipulate that every node is strongly connected to itself.

Strong connection is an equivalence relation, i.e., it is reflective, symmetric and transitive. (EXERCISE: Prove this.) Weak connection is also an equivalence relation. (EXERCISE: Prove this.) Therefore, a graph can be divided into non-overlapping strongly connected components, consisting of maximal sets of nodes which are all strongly connected to each other. (In Figure K.1, A, B and C form one strongly connected component, and D and E form components with just one node.) It can also be divided into weakly connected components, maximal sets of nodes which are all weakly connected to each other. (There is only one weakly connected component in the graph. If either of the edges into D were removed, there would be two weakly connected components.)

A cycle is a directed path from a node to itself. The existence of two distinct nodes which are strongly connected to each other implies the existence of a cycle, and vice versa. A directed graph without cycles is called acyclic. Said another way, an acyclic graph is one where all the strongly connected components consist of individual nodes. The weakly connected components can however contain an unlimited number of nodes.

In a directed acyclic graph, or DAG, it is common to refer to the nodes connected by an edge as “parent” and “child” (so that the arrow runs from the parent to the child). If there is a directed path from V1 to V2, then V1 is the ancestor of V2, which is the descendant of V1. In the jargon, the ancestor/descendant relation is the transitive closure of the parent/child relation.

￼[1] Or, more rarely, a Guthrie diagram.
